
#' Calculate homogeneity scores for orthogroups
#'
#' @param orthogroup_df Data frame with orthogroups and their associated genes
#' and annotation. The columns \strong{Gene}, \strong{Orthogroup}, and
#' \strong{Annotation} are mandatory, and they must represent Gene ID,
#' Orthogroup ID, and Annotation ID (e.g., Interpro/PFAM), respectively.
#'
#' @return A 2-column data frame with the variables \strong{Orthogroup}
#' and \strong{mean_H}, corresponding to orthogroup ID and mean homogeneity,
#' respectively.
#' @export
#' @rdname calculate_H
#' @importFrom dplyr group_by summarise mutate ungroup select distinct n
#' @examples
#' data(og)
#' data(interpro_ath)
#' orthogroup_df <- merge(og[og$Species == "Ath", ], interpro_ath)
#' H <- calculate_H(orthogroup_df)
calculate_H <- function(orthogroup_df = NULL) {

    h <- dplyr::group_by(orthogroup_df, Orthogroup, Annotation)
    h <- dplyr::summarise(h, n = dplyr::n())
    h <- dplyr::mutate(h, H = n / sum(n), mean_H = mean(H))
    h <- dplyr::ungroup(h)
    h <- dplyr::select(h, Orthogroup, mean_H)
    h <- as.data.frame(dplyr::distinct(h, .keep_all = TRUE))
    return(h)
}

#' Assess orthogroup inference based on functional annotation
#'
#'
#' @param orthogroups A 3-column data frame with columns \strong{Orthogroup},
#' \strong{Species}, and \strong{Gene}. This data frame can be created from
#' the 'Orthogroups.tsv' file generated by OrthoFinder with the function
#' \code{read_orthogroups()}.
#' @param annotation A list of 2-column data frames with columns
#' \strong{Gene} (gene ID) and \strong{Annotation} (annotation ID).
#' The names of list elements must correspond to species names as
#' in the second column of \emph{orthogroups}. For instance, if there are
#' two species in the \emph{orthogroups} data frame named
#' "SpeciesA" and "SpeciesB", \emph{annotation} must be a
#' list of 2 data frames, and each list element must be named
#' "SpeciesA" and "SpeciesB".
#'
#' @return A data frame.
#' @rdname assess_orthogroups
#' @export
#' @examples
#' data(og)
#' data(interpro_ath)
#' data(interpro_bol)
#' # Subsetting annotation for demonstration purposes. Do not subset.
#' annotation <- list(Ath = interpro_ath[1:1000,], Bol = interpro_bol[1:1000,])
#' assess <- assess_orthogroups(og, annotation)
assess_orthogroups <- function(orthogroups = NULL, annotation = NULL) {

    og_list <- split(orthogroups, orthogroups$Species)
    og_list <- lapply(seq_along(og_list), function(x) {
        species <- names(og_list)[x]
        idx <- which(names(annotation) == species)
        merged <- merge(og_list[[x]], annotation[[idx]])
        names(merged)[4] <- "Annotation"
        H <- calculate_H(merged)
        names(H) <- c("Orthogroups", paste0(species, "_H"))
        return(H)
    })

    merge_func <- function(x, y) {
        merge(x, y, by = "Orthogroups", all = TRUE)
    }
    final_df <- Reduce(merge_func, og_list)
    means <- apply(final_df[, -1], 1, mean, na.rm = TRUE)
    final_df$Mean_H <- means
    return(final_df)
}
